### ISSUE TITLE
NoSuchServiceException in tutorial code about services

### ISSUE THREAD

**Issue by haesleinhuepf** [imagej/imagej-tutorials#28]
Hey guys,

I was just trying the "Create a new Plugin Type" example, because I'm really curious on how to use this plugin mechanism. The code is located here: 

https://github.com/imagej/imagej-tutorials/tree/master/create-a-new-plugin-type

When I run it (main function in CreateANewPluginType), I get this error meassage:

```
Exception in thread "main" org.scijava.NoSuchServiceException: Service AnimalService not found.
	at org.scijava.Context.service(Context.java:309)
	at org.scijava.AbstractGateway.get(AbstractGateway.java:116)
	at CreateANewPluginType.main(CreateANewPluginType.java:93)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```
And this is the line, where the error happens:

`final AnimalService animals = ij.get(AnimalService.class);`

I'm running on Java 1.8.0_66_jdk on MacOS 10.10.5 (inside IntelliJ 2016.1)

Thanks!
Robert

**Comment by haesleinhuepf** [comment]
I just figured out how to make the tutorial work: If I replace the line


```

final AnimalService animals = ij.get(AnimalService.class);

```

with these lines:

```

Context context = new Context(AnimalService.class);
final AnimalService animals = context.getService(AnimalService.class);

```

It works. But is it intended to be like that? Is there an alternative of adding a new service to an existing Context?

Thanks!
Robert

**Comment by stelfrich** [comment]
@haesleinhuepf I can reproduce the issue.

It is due to some changes on how the ImageJ gateway works. Prior to https://github.com/imagej/imagej/commit/2f1ecc38960a76b72074f5bc68dca06929992f50 `new ImageJ()` would create a `Context` with all available services (including `AnimalService`). Introduced with the mentioned commit, the created `Context` only contains relevant services.

I think this example could be a good point to introduce custom `Context`s. If I am not mistaken, all the other examples use a `Context` generated by `ImageJ`. What do you think, @ctrueden?

**Comment by ctrueden** [comment]
We can either write `new Context()` or else make `AnimalService` implement `ImageJService`. I think I prefer the former solution.

**Comment by ctrueden** [comment]
Looking at the tutorial, it is very ImageJ-centric. (Even though it doesn't really do anything with images, and could be repurposed as a SciJava-level service.)

So I'm going to change it to implement `ImageJService`, and then this problem goes away.

**Comment by haesleinhuepf** [comment]
Thanks a lot guys! :)
