### ISSUE TITLE
ij.platform().open(new URL("http://imagej.net/")) failed on Windows 10

### ISSUE THREAD

**Issue by panovr** [imagej/imagej-tutorials#34]
On my Windows 10, this statement in `intro-to-imagej-api` repo will fail:
`ij.platform().open(new URL("http://imagej.net/"));`
I think maybe this is a Java related issue.

**Comment by ctrueden** [comment]
See also scijava/scijava-common#231.

@panovr Could you please investigate? I suggest using the debugger, setting a breakpoint in the `open` method of `DefaultPlatformService`. This fix might be easy. And if not, more information about what is going on under the hood would be helpful.

**Comment by panovr** [comment]
@ctrueden I will investigate this issue.

**Comment by panovr** [comment]
@ctrueden I did more investigation on this issue. Basically, the open() method will invoke the open() method in WindowsPlatform.java https://github.com/scijava/scijava-plugins-platforms/blob/master/src/main/java/org/scijava/plugins/platforms/windows/WindowsPlatform.java#L56

```
        @Override
	public void open(final URL url) throws IOException {
		final String cmd;
		if (System.getProperty("os.name").startsWith("Windows 2000")) {
			cmd = "rundll32 shell32.dll,ShellExec_RunDLL";
		}
		else cmd = "rundll32 url.dll,FileProtocolHandler";
		if (getPlatformService().exec(cmd, url.toString()) != 0) {
			throw new IOException("Could not open " + url);
		}
	}
```
And it will invoke the exec() method in DefaultPlatformService.java https://github.com/scijava/scijava-common/blob/master/src/main/java/org/scijava/platform/DefaultPlatformService.java#L116
 ```
@Override
	public int exec(final String... args) throws IOException {
		final Process process = Runtime.getRuntime().exec(args);
		try {
			process.waitFor();
			return process.exitValue();
		}
		catch (final InterruptedException ie) {
			throw new IOException("InterruptedException during execution: " +
				ie.getMessage());
		}
	}
```
The key is the **args** parameter: in above exec method, the parameter args will be assigned as String array: ["rundll32 url.dll,FileProtocolHandler", "http://imagej.net"].
However, Runtime.getRuntime().exec(args) will throw an Exception if the args is a String array.

Instead, if we concatenate the String array as a single String object like:
cmd = "rundll32 url.dll,FileProtocolHandler ";  // **note the trailing space!**
url = "http://imagej.net";
final String link = cmd + url;
Runtime.getRuntime().exec(link)

Then it just works fine on my Windows 10.

**Comment by ctrueden** [comment]
@panovr That is quite odd! Certainly, there is an `exec` method which accepts a `String[]` and it purports to treat the array elements as separate arguments. Did you try it the other way?
```java
cmd = "rundll32"
args = ["url.dll,FileProtocolHandler", url.toString()]
```
If that doesn't work, could you please research the best way on Windows 10 to do this from Java? Surely there are threads e.g. on StackOverflow about it.

**Comment by panovr** [comment]
@ctrueden I will try other ways tomorrow morning and let you know the result.

**Comment by panovr** [comment]
@ctrueden You are right, the correct parameters construction should be:
```
        final String url = "http://imagej.net";
        final String cmd = "rundll32";
        open(cmd, "url.dll,FileProtocolHandler", url.toString());
```
So the key is to separate "rundll32" into a single String object.

**Comment by ctrueden** [comment]
@panovr Great! Would you please fix it? Thank you!

**Comment by panovr** [comment]
@ctrueden Done, please do code review and merge the pull request.
